# Generated by Django 4.0.4 on 2022-04-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_alter_lugar_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.lugar')),
            ],
        ),
    ]
