# Generated by Django 4.0.4 on 2022-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_alter_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=30, null=True),
        ),
    ]
