# Generated by Django 4.0.4 on 2022-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_persona_estado_civil_persona_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=13),
        ),
    ]
